name: clang-tidy-review

# You can be more specific, but it currently only works on pull requests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build & Test
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{ runner.workspace }}/build
        # will set the CC & CXX for cmake
        cc: gcc
        cxx: g++
        build-type: Release
        configure-options: -DCMAKE_EXPORT_COMPILE_COMMANDS=ON



    - uses: ZedThree/clang-tidy-review@v0.9.0
      id: review
      with:
        build_dir: ./build
    # If there are any comments, fail the check
    - if: steps.review.outputs.total_comments > 0
      run: exit 1