name: clang-tidy-review

# You can be more specific, but it currently only works on pull requests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get latest CMake and ninja
      uses: lukka/get-cmake@latest

    - name: Install Curl
      run: sudo apt install -y libcurl-dev

    - name: Generate Makefiles
      run: |
        mkdir _build;
        cd _build;
        cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    - name: Run clang-tidy
      uses: TheArtfulBodger/action-clang-tidy@master
      with:
        scandir: '.'
        builddir: 'build'
        excludedirs: 'ext,build'
        extensions: 'c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx'
