name: clang-format Check
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'common'
          - 'plugins'
          - 'pluginspec'
          - 'tools'
          - 'tdd'
    steps:
    - uses: actions/checkout@v2
    - uses: jidicula/clang-format-action@v4.9.0
      with:
        clang-format-version: '14'
        check-path: ${{ matrix.path }}
        fallback-style: 'WebKit'