name: clang-tidy-review

# You can be more specific, but it currently only works on pull requests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build & Test
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{ runner.workspace }}/build
        # will set the CC & CXX for cmake
        cc: gcc
        cxx: g++
        build-type: Release
        configure-options: -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    - name: Run clang-tidy
      uses: TheArtfulBodger/action-clang-tidy@master
      with:
        scandir: '.'
        builddir: 'build'
        excludedirs: 'ext,build'
        extensions: 'c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx'
