name: build

# You can be more specific, but it currently only works on pull requests
on: [pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get latest CMake and ninja
      uses: lukka/get-cmake@latest
    
    - name: Generate Makefiles
      run: |
        mkdir _build;
        cd _build;
        cmake ..

    - name: Build
      run: | 
        cd _build;
        cmake --build .